language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli
install:
- npm install
env:
  global:
    secure: H11OJg5PFYv3XiLdng/L/xxti/Z7bK0kPFivd9w7NncIj+LvqEvbsR4yxuVcm/gizPz06e9hC9zIEAMmzVAMWW0OBQyY1p5jd13TzYpCuJv3W8FBa3rRdOL4TIlhkqGL0KU2AMMKyqZvOhdnw7UmijZIgUGlr9RMHBWafA0bpOE=
